### PR TITLE
Add a blog post for the 1.15.0 release

### PR DESCRIPTION
**Pull request by anthonybilinski**
Features and fixes may have one or two items added based on to-be-merged PRs.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/blog/14)

### CODE REVIEW

**Comment by anthonybilinski** [comment]
Updated based on feedback from @tox-user.

**Comment by tox-user** [comment]
> date:   2018-4-18

date:   2018-04-18


> # Stability
>Hi, qTox fans! 1.15.0 is now released with many bug fixes, a couple minor features, as well as updating >to the recently released [toxcore](https://github.com/TokTok/c-toxcore) 0.2.2, with important security >fixes.

I wonder if we should tell users to update immediately, because of the vulnerability. I don't see any announcements about it on the blog (https://blog.tox.chat) or on reddit. So many people wanted to release a fix as soon as possible, but now for some reason nobody is telling users to update. Should we be the first? It's the only reason for this release.


>- reduced memory usage
>- add abilitiy to disable LAN discovery and disable notifications
>- added support for higher res (1440p and 4k) webcams

Perhaps past tense tense should be used? There is a typo in word ability - it says "abilitiy".

**Comment by anthonybilinski** [comment]
Fixed date, added past tense, fixed spelling.

I think it's a good idea to have a post about the vulnerability on blog.tox.chat which we can link to? It seems impossible to give proper scope of the problem within our quick 1 sentence blurb for the qTox release (i.e. explaining how upgrading yourself doesn't actually protect you, but strengthens the network protecting others, how IP is protected normally and what part of that is broken by vulnerability, difficulty of attack etc.)

**Comment by tox-user** [comment]
>- fix many crashes
>- fix distorted audio when gain is non-default

You should change those to past tense as well.

> It seems impossible to give proper scope of the problem within our quick 1 sentence blurb for the qTox release 

That's a good point. Maybe we should describe it briefly and link to a github issue and PR? People should know that this release contains important security fixes and they should update as soon as possible.

**Comment by anthonybilinski** [comment]
Updated two tenses, linked to PR instead of issue because it has more discussion about impact. We can update to a blog post which is clearer for users if/when tox.chat has one.

**Comment by anthonybilinski** [comment]
Release is now out, ready to publish blog once review is done.

**Comment by anthonybilinski** [comment]
update from PR link to tox.chat blog post: https://blog.tox.chat/2018/04/security-vulnerability-and-new-toxcore-release/ and updated post date from 18th to 19th.

**Comment by anthonybilinski** [comment]
Going to push as is so we can mention it with the toxcore announcement on reddit etc. We can update if there's more review.

EDIT: jk don't have permission :D

**Comment by anthonybilinski** [comment]
maybe before we post, https://tox.chat/download.html mac builds are pointed to github's 1.15.0, but the windows builds are still pointed to build.tox.chat. What are we going to do about nightlies for window? Keep nighties at build.tox.chat but move stable releases to github?

**Comment by tox-user** [comment]
> # Stability

maybe # Stability improvements and security fix
add some sort of warning that users should update to qTox 1.15 or else their computer will blow up or something. If they compile themselves they need to get new toxcore. It's the whole point of this early release.Wwe need to scare the user into updating. The future of Tox DHT depends on it :)

**Comment by anthonybilinski** [comment]
Updated post date.

Changed title to "Stability improvements and security fix".
>else their computer will blow up or something
>Wwe need to scare the user into updating

I really disagree with something over the top like that. The security issue is mentioned in our 1 sentence and a full explanation is linked to. We even add "important" to urge users to update, but I don't think telling them the world will end if they don't update is good, especially since an individual updating doens't actually provide them personal benefit, it just slightly strengthens the network. I also worry that if we call a possible IP leak a very scary security problem that will blow up their computers, we might have "The Boy Who Cried Wolf" syndrome, and if we do have a security vulnerability in the future which is more serious, people could ignore our post thinking it's a relatively minor security vulnerability. I've left that part unchanged.


@sudden6 re: what do we do about windows nightlies for tox.chat?

**Comment by tox-user** [comment]
Even if one of the nodes in the path is updated they are protected. I think it matters. **If this issue wasn't critical why did we release so soon?** From user's perspective there aren't many reasons to update, because users mostly care about new features.

**Comment by anthonybilinski** [comment]
I absolutely agree it matters, which is why we say it's important, link to an explanation, and have a release. I just don't think we should have sensationalist language blow it out of proportion. If "important security fix" isn't enough to motivate them to update, then they won't update.

**Comment by sudden6** [comment]
@anthonybilinski not sure, do we want to provide nightlies via Github too? it's certainly possible, but for now I'd leave it and concentrate on providing an AppImage for releases too.

As far as the security issue goes I agree with @anthonybilinski the wording seems sufficient, IMO the saving own messages without history enabled is an even bigger issue.

**Comment by sudden6** [comment]
for the blog post, IMO we should thank the translators too, maybe as a group by linking to our weblate page?

**Comment by anthonybilinski** [comment]
Added translations under "features and fixes" and added translators as a group under contributors.

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/blog/14#-:-LAZpOHr4lVh-sFr-m5a:bnfp4nl)*

**Comment by tox-user** [comment]
>IMO the saving own messages without history enabled is an even bigger issue.

It's definitely an important security issue that should also be explained in the post (currently it isn't). If you think it is a bigger issue than a critical toxcore vulnerability that allows to deanonymize users, why didn't we release a quick fix? That small note about important security fixes is too hard to miss. There is a blog post on tox.chat about this vulnerability now, but it doesn't hurt to make sure people know about it. We want everyone to update as soon as they can. If we didn't, why did you rush to make this release?

I just don't understand. Is it a serious vulnerability or not? If it is, we should be telling everyone on IRC, github, reddit and everywhere else to update.

**Comment by anthonybilinski** [comment]
>should also be explained in the post (currently it isn't)

It's listed under "Features and fixes" as "- don't save own messages when history is disabled". I added a sub-point that goes into more detail about when it was introduced and how to clear history, and moved this "fix" to the top of our list.

>why didn't we release a quick fix

Maybe we should have, but it's too late to patch release it now and it's included in v1.15.0.

>That small note about important security fixes is too hard to miss

we mention the security fix in the title of the post and it's half of the written content before the enumerated features and fixes, and link to the long post on blog.tox.chat. I don't think going into details about the attack, impact, difficulty, etc when it's already written by toxcore and linked to by us makes sense for us to do as a client.

>We want everyone to update as soon as they can. If we didn't, why did you rush to make this release?

Yes we do want people to update, no one's saying otherwise. I'm just against exaggerating problems to scare people into updating. I think we should present the objective problem and let them choose if they want to update.

>I just don't understand. Is it a serious vulnerability or not? If it is, we should be telling everyone on IRC, github, reddit and everywhere else to update.

It's fairly serious yes, that's why we're making this release and blog post, and as soon as this is published we can post it around the web, IRC, and tox groups asking everyone to update.

Only change was adding more info on the history disabling bug.

**Comment by tox-user** [comment]
Looks good.

**Comment by anthonybilinski** [comment]
Still need the magic "LGTM" and a merge :)

EDIT: nvm, got merge permission

**Pull request merged**
