### PR TITLE
Add a blog post for the 1.14.0 release

### PR DESCRIPTION
**Pull request by tox-user**
This change is [Reviewable](https://reviewable.io/reviews/qtox/blog/11)

### CODE REVIEW

**Comment by sudden6** [comment]
@anthonybilinski assigned to you for language fixes :)

content lgmt :)

**Comment by anthonybilinski** [comment]
language LGTM

content:
* I'd remove "small" from "small features and fixes", I'd say history search and HD video (from toxcore 0.2) are pretty major for a minor release bump of qTox.
* I'd change "Plus it works with recently released [toxcore](https://github.com/TokTok/c-toxcore) 0.2.0 and 0.2.1!" to "Plus qTox now officially supports recently released toxcore 0.2.0 and 0.2.1 with HD video fix, so make sure to update toxcore following [compilation instructions](https://github.com/qTox/qTox/blob/master/INSTALL.md#compile-toxcore) if you compiled qtox yourself."
    * I know this isn't qTox's change directly, but from a user's perspective I think it's a pretty major fix between qTox 1.13 and qTox 1.14.
* Under "Features and fixes" I might include "Improved webcam detection on windows" since https://github.com/qTox/qTox/issues/4764 seemed like a fairly widespread issue
* I'm not sure about "greedy cat" grabbing money because of "Tox Foundation's" financial history... We're unrelated administratively, but it might not be best to remind people of the ugly past.

let me know if people agree/disagree on points.

**Comment by tox-user** [comment]
If we are going to have a release 1.14.1, we should mention it in this blog post, then publish it and create a separate blog post for 1.14.1 when 1.14.1 is released. I hope it will come out in a few days after some testing. In that case we could now tell people to wait those few days for bug fixes.

Or we can not release this blog post and pretend 1.14.0 never happened.

**Comment by tox-user** [comment]
> remove "small" from "small features and fixes"

Done.

> I'd change "Plus it works with recently released toxcore 0.2.0 and 0.2.1!" to "Plus qTox now officially supports recently released toxcore 0.2.0 and 0.2.1 with HD video fix, so make sure to update toxcore following compilation instructions if you compiled qtox yourself."
    I know this isn't qTox's change directly, but from a user's perspective I think it's a pretty major fix between qTox 1.13 and qTox 1.14.

I disagree. Everyone runs a different version of toxcore, so it's not that much related to qTox. It's something that should be mentioned in Tox blog.

> Under "Features and fixes" I might include "Improved webcam detection on windows" since qTox/qTox#4764 seemed like a fairly widespread issue

Done.

> I'm not sure about "greedy cat" grabbing money because of "Tox Foundation's" financial history... We're unrelated administratively, but it might not be best to remind people of the ugly past.

I don't think people will see it that way. It's just a cat picture :).

**Comment by sudden6** [comment]
lgtm

**Pull request merged**
