### PR TITLE
Blog post about the new qTox release cycle

### PR DESCRIPTION
**Pull request by sudden6**
This change is [Reviewable](https://reviewable.io/reviews/qtox/blog/3)

### CODE REVIEW

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

_[_posts/2016-10-28-New-Release-Cycle, line 31 at r1](https://reviewable.io:443/reviews/qtox/blog/3#-KVBaFXZI_XRtdcfm4n0:-KVBaFXZI_XRtdcfm4n1:b-z5g052) ([raw file](https://github.com/qtox/blog/blob/d01c282cb2b2624c32621ae2472c9ced5b439990/_posts/2016-10-28-New-Release-Cycle#L31)):_

> ```
> features and the last week is a stabilizing phase.
> 
> During the first part anyone is welcomed to send their pull requests(PRs) about
> ```

space between `requests` and `(PRs)`

---

_[_posts/2016-10-28-New-Release-Cycle, line 38 at r1](https://reviewable.io:443/reviews/qtox/blog/3#-KVB_VgcuxesnRl8O98n:-KVB_VgcuxesnRl8O98o:b-o4zsvx) ([raw file](https://github.com/qtox/blog/blob/d01c282cb2b2624c32621ae2472c9ced5b439990/_posts/2016-10-28-New-Release-Cycle#L38)):_

> ```
> # Cool, how can I help?
> 
> Well, a good first start is always to look at our [README][readme] or to
> ```

Could be just [README] here and in the "footer", but that works

---

_[_posts/2016-10-28-New-Release-Cycle, line 41 at r1](https://reviewable.io:443/reviews/qtox/blog/3#-KVB_jNKED2DFM9LBSDL:-KVB_jNKED2DFM9LBSDM:bbitzxg) ([raw file](https://github.com/qtox/blog/blob/d01c282cb2b2624c32621ae2472c9ced5b439990/_posts/2016-10-28-New-Release-Cycle#L41)):_

> ```
> checkout our IRC channel [#qtox@freenode.net][IRC-channel]. The README has
> a list with various ways to help qTox, from non-Programmer tasks to Code-Guru
> level. On the IRC we will be glad for any feedback you give :)
> ```

"We will be glad for any feedback, be it on IRC, in the issues or on the [mailing list] :)"

`[mailing list]: https://lists.tox.chat/listinfo/general`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/3)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[_posts/2016-10-28-New-Release-Process.md, line 38 at r2](https://reviewable.io:443/reviews/qtox/blog/3#-KVBgXRyUQ9PjCWkcC9H:-KVBgXRyUQ9PjCWkcC9I:b-ip5sie) ([raw file](https://github.com/qtox/blog/blob/deb1973533fd00740cc02d8d355f0cca1cfdb5b2/_posts/2016-10-28-New-Release-Process.md#L38)):_

> ``` Markdown
> # Cool, how can I help?
> 
> Well, a good first start is always to look at our [README] or to
> ```

`s/Well, a/A/` ?

---

_[_posts/2016-10-28-New-Release-Process.md, line 39 at r2](https://reviewable.io:443/reviews/qtox/blog/3#-KVBgklqNkDaGoWXEfA_:-KVBgklqNkDaGoWXEfAa:bkefe51) ([raw file](https://github.com/qtox/blog/blob/deb1973533fd00740cc02d8d355f0cca1cfdb5b2/_posts/2016-10-28-New-Release-Process.md#L39)):_

> ``` Markdown
> 
> Well, a good first start is always to look at our [README] or to
> checkout our IRC channel [#qtox@freenode.net][IRC-channel]. The README has
> ```

`s/checkout/check out/`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/3)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[_posts/2016-10-28-New-Release-Process.md, line 39 at r3](https://reviewable.io:443/reviews/qtox/blog/3#-KVBixEvsFrrlzdYPehh:-KVBixEvsFrrlzdYPehi:b-d8gh65) ([raw file](https://github.com/qtox/blog/blob/983c712c6d753f53e164dfb7af2d8a93f32ca879/_posts/2016-10-28-New-Release-Process.md#L39)):_

> ``` Markdown
> 
> A good first start is always to look at our [README] or to
> check out our IRC channel [#qtox@freenode.net][IRC-channel]. The README has
> ```

```
A good first start can begin by looking at our [README] and/or checking out
our
```

?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/3)_

**Comment by initramfs** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[_posts/2016-10-28-New-Release-Process.md, line 16 at r4](https://reviewable.io:443/reviews/qtox/blog/3#-KVFdnDf7qJjKRq69EC1:-KVFdnDgiOuBkfhEwFCK:b-3kuf81) ([raw file](https://github.com/qtox/blog/blob/40b3c3088ca58b580dc3dd5c0216cf6101657a20/_posts/2016-10-28-New-Release-Process.md#L16)):_

> ``` Markdown
> Currently qTox has no fixed release cycle. That means we do a release when
> we feel like doing a release, which can be at any given interval. We
> determined this approach is not really fitting qTox.
> ```

"not really fitting qTox." -> "not really fitting for qTox." or "not really fitting for a project like qTox."

---

_[_posts/2016-10-28-New-Release-Process.md, line 40 at r4](https://reviewable.io:443/reviews/qtox/blog/3#-KVFg-WTNaSzNxYZeQ2M:-KVFg-WTNaSzNxYZeQ2N:b-80zq7q) ([raw file](https://github.com/qtox/blog/blob/40b3c3088ca58b580dc3dd5c0216cf6101657a20/_posts/2016-10-28-New-Release-Process.md#L40)):_

> ``` Markdown
> A good first start is always to look at our [README] or to
> check out our IRC channel [#qtox@freenode.net][IRC-channel]. The README has
> a list with various ways to help qTox, from non-Programmer tasks to Code-Guru
> ```

```
...a list with various ways to help qTox, from non-Programmer tasks to Code-Guru level.
```

changed to

```
...a list of various ways to help qTox, ranging from non-programming maintenance tasks to features and/or bugfixes that need to be implemented.
```

---

_[_posts/2016-10-28-New-Release-Process.md, line 51 at r4](https://reviewable.io:443/reviews/qtox/blog/3#-KVFjV9anp9pNHFsCvqV:-KVFjV9bpDgfMOEJVZWz:b24w5jo) ([raw file](https://github.com/qtox/blog/blob/40b3c3088ca58b580dc3dd5c0216cf6101657a20/_posts/2016-10-28-New-Release-Process.md#L51)):_

> ``` Markdown
> 
> 
> [readme]: https://github.com/qTox/qTox/tree/e8e946d4c8f21e55680ab7ff8ea0a60026b399e2#help-us
> ```

This link points to a specific commit, shouldn't it point to master? Or perhaps a specific tag?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/3)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[_posts/2016-10-28-New-Release-Process.md, line 51 at r4](https://reviewable.io:443/reviews/qtox/blog/3#-KVFjV9anp9pNHFsCvqV:-KVFl5mMKywj9Jl0xy03:b6zjq23) ([raw file](https://github.com/qtox/blog/blob/40b3c3088ca58b580dc3dd5c0216cf6101657a20/_posts/2016-10-28-New-Release-Process.md#L51)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> This link points to a specific commit, shouldn't it point to master? Or perhaps a specific tag?
> </details>
> There's no tag, and link on master could possibly change in the future.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/3)_

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

_[_posts/2016-10-28-New-Release-Process.md, line 38 at r1](https://reviewable.io:443/reviews/qtox/blog/3#-KVB_VgcuxesnRl8O98n:-KVFlulmgDYaDqt5uLP-:b-896fix) ([raw file](https://github.com/qtox/blog/blob/d01c282cb2b2624c32621ae2472c9ced5b439990/_posts/2016-10-28-New-Release-Process.md#L38)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Could be just [README] here and in the "footer", but that works
> </details>
> Done.

---

_[_posts/2016-10-28-New-Release-Process.md, line 38 at r2](https://reviewable.io:443/reviews/qtox/blog/3#-KVBgXRyUQ9PjCWkcC9H:-KVFlwGMpiYB8rbK4KaU:b-896fix) ([raw file](https://github.com/qtox/blog/blob/deb1973533fd00740cc02d8d355f0cca1cfdb5b2/_posts/2016-10-28-New-Release-Process.md#L38)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> `s/Well, a/A/` ?
> </details>
> Done.

---

_[_posts/2016-10-28-New-Release-Process.md, line 39 at r2](https://reviewable.io:443/reviews/qtox/blog/3#-KVBgklqNkDaGoWXEfA_:-KVFlxGVUCtZUihOZ2hZ:b-896fix) ([raw file](https://github.com/qtox/blog/blob/deb1973533fd00740cc02d8d355f0cca1cfdb5b2/_posts/2016-10-28-New-Release-Process.md#L39)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> `s/checkout/check out/`
> </details>
> Done.

---

_[_posts/2016-10-28-New-Release-Process.md, line 51 at r4](https://reviewable.io:443/reviews/qtox/blog/3#-KVFjV9anp9pNHFsCvqV:-KVFm3v52T_Taub38wZR:bdtywqv) ([raw file](https://github.com/qtox/blog/blob/40b3c3088ca58b580dc3dd5c0216cf6101657a20/_posts/2016-10-28-New-Release-Process.md#L51)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> There's no tag, and link on master could possibly change in the future.
> </details>
> exactly what zetok said.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/3)_

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

_[_posts/2016-10-28-New-Release-Process.md, line 31 at r1](https://reviewable.io:443/reviews/qtox/blog/3#-KVBaFXZI_XRtdcfm4n0:-KVFmx0VUxopb3152XeA:b-896fix) ([raw file](https://github.com/qtox/blog/blob/d01c282cb2b2624c32621ae2472c9ced5b439990/_posts/2016-10-28-New-Release-Process.md#L31)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> space between `requests` and `(PRs)`
> </details>
> Done.

---

_[_posts/2016-10-28-New-Release-Process.md, line 41 at r1](https://reviewable.io:443/reviews/qtox/blog/3#-KVB_jNKED2DFM9LBSDL:-KVFmHDABafr61k8eQVZ:b-896fix) ([raw file](https://github.com/qtox/blog/blob/d01c282cb2b2624c32621ae2472c9ced5b439990/_posts/2016-10-28-New-Release-Process.md#L41)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> "We will be glad for any feedback, be it on IRC, in the issues or on the [mailing list] :)"
> 
> `[mailing list]: https://lists.tox.chat/listinfo/general`
> </details>
> Done.

---

_[_posts/2016-10-28-New-Release-Process.md, line 39 at r3](https://reviewable.io:443/reviews/qtox/blog/3#-KVBixEvsFrrlzdYPehh:-KVFn-tc0tUNsG39GHuk:b-6itkfd) ([raw file](https://github.com/qtox/blog/blob/983c712c6d753f53e164dfb7af2d8a93f32ca879/_posts/2016-10-28-New-Release-Process.md#L39)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> ```
> A good first start can begin by looking at our [README] and/or checking out
> our
> ```
> 
> ?
> </details>
> I like it better the way it is.

---

_[_posts/2016-10-28-New-Release-Process.md, line 16 at r4](https://reviewable.io:443/reviews/qtox/blog/3#-KVFdnDf7qJjKRq69EC1:-KVFmvWvqyUeoJ-5ulrp:b-896fix) ([raw file](https://github.com/qtox/blog/blob/40b3c3088ca58b580dc3dd5c0216cf6101657a20/_posts/2016-10-28-New-Release-Process.md#L16)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> "not really fitting qTox." -> "not really fitting for qTox." or "not really fitting for a project like qTox."
> </details>
> Done.

---

_[_posts/2016-10-28-New-Release-Process.md, line 40 at r4](https://reviewable.io:443/reviews/qtox/blog/3#-KVFg-WTNaSzNxYZeQ2M:-KVFn3r1KWMPWhjUTGIn:b-896fix) ([raw file](https://github.com/qtox/blog/blob/40b3c3088ca58b580dc3dd5c0216cf6101657a20/_posts/2016-10-28-New-Release-Process.md#L40)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> ```
> ...a list with various ways to help qTox, from non-Programmer tasks to Code-Guru level.
> ```
> 
> changed to
> 
> ```
> ...a list of various ways to help qTox, ranging from non-programming maintenance tasks to features and/or bugfixes that need to be implemented.
> ```
> 
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/3)_

**Comment by initramfs** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[_posts/2016-10-28-New-Release-Process.md, line 51 at r4](https://reviewable.io:443/reviews/qtox/blog/3#-KVFjV9anp9pNHFsCvqV:-KVFno7J2w6QqrumiLsI:b2xq40s) ([raw file](https://github.com/qtox/blog/blob/40b3c3088ca58b580dc3dd5c0216cf6101657a20/_posts/2016-10-28-New-Release-Process.md#L51)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> exactly what zetok said.
> </details>
> Ok. Just wanted to make sure.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/3)_

**Comment by Diadlo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/3#-:-KVHBsEGFxkdyu9tYwFm:bnfp4nl)_

**Comment by zetok** [comment]
Reviewed 1 of 3 files at r2, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/3)_

**Comment by zetok** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/3#-:-KVHT1hAh8847e7_kjx9:bnfp4nl)_

**Pull request merged**
