### PR TITLE
Create 2017-02-15-Maintainer-Wanted.md

### PR DESCRIPTION
**Pull request by sudden6**
This change is [Reviewable](https://reviewable.io/reviews/qtox/blog/7)

### CODE REVIEW

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[_posts/2017-02-15-Maintainer-Wanted.md, line 11 at r1](https://reviewable.io:443/reviews/qtox/blog/7#-Kd22cSgEtHPQSfUq1P4:-Kd22cShSn8wCKuUIotN:bodtm7i) ([raw file](https://github.com/qtox/blog/blob/380dcb9f572b927194ebafb333e1995e0b499c88/_posts/2017-02-15-Maintainer-Wanted.md#L11)):*
> ```Markdown
> # Outdated Linux packages
> 
> Since many of you noticed, the packages for Linux in the
> ```

`s/Since/As/` ?

---

*[_posts/2017-02-15-Maintainer-Wanted.md, line 18 at r1](https://reviewable.io:443/reviews/qtox/blog/7#-Kd22oxA18L3ac0s9MOc:-Kd22oxB_eYxR5LGq4hy:b-52qm0d) ([raw file](https://github.com/qtox/blog/blob/380dcb9f572b927194ebafb333e1995e0b499c88/_posts/2017-02-15-Maintainer-Wanted.md#L18)):*
> ```Markdown
> # What do I have to do?
> 
> Packaging work is mostly about keeping bash scripts for the build up to date.
> ```

`s/build/builds/`, there are multiple packages

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/7)*

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[_posts/2017-02-15-Maintainer-Wanted.md, line 33 at r1](https://reviewable.io:443/reviews/qtox/blog/7#-Kd23NEKMhoH--zWrKyy:-Kd23NEKMhoH--zWrKyz:bxofd6e) ([raw file](https://github.com/qtox/blog/blob/380dcb9f572b927194ebafb333e1995e0b499c88/_posts/2017-02-15-Maintainer-Wanted.md#L33)):*
> ```Markdown
> 
> If you're interested in helping your favourite FOSS project or want to know
> more, take a look at our [IRC channel] or [this github issue].
> ```

`s/IRC channel/#qtox @ freenode IRC channel/`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/7)*

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[_posts/2017-02-15-Maintainer-Wanted.md, line 11 at r1](https://reviewable.io:443/reviews/qtox/blog/7#-Kd22cSgEtHPQSfUq1P4:-Kd258E-ga1Gdjjc6G5b:b-896fix) ([raw file](https://github.com/qtox/blog/blob/380dcb9f572b927194ebafb333e1995e0b499c88/_posts/2017-02-15-Maintainer-Wanted.md#L11)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

`s/Since/As/` ?
</blockquote></details>

Done.

---

*[_posts/2017-02-15-Maintainer-Wanted.md, line 18 at r1](https://reviewable.io:443/reviews/qtox/blog/7#-Kd22oxA18L3ac0s9MOc:-Kd259lEc63ze59J_tOB:b-896fix) ([raw file](https://github.com/qtox/blog/blob/380dcb9f572b927194ebafb333e1995e0b499c88/_posts/2017-02-15-Maintainer-Wanted.md#L18)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

`s/build/builds/`, there are multiple packages
</blockquote></details>

Done.

---

*[_posts/2017-02-15-Maintainer-Wanted.md, line 33 at r1](https://reviewable.io:443/reviews/qtox/blog/7#-Kd23NEKMhoH--zWrKyy:-Kd25BFpWGhD33DPHYnm:b-896fix) ([raw file](https://github.com/qtox/blog/blob/380dcb9f572b927194ebafb333e1995e0b499c88/_posts/2017-02-15-Maintainer-Wanted.md#L33)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

`s/IRC channel/#qtox @ freenode IRC channel/`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/7)*

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[_posts/2017-02-15-Maintainer-Wanted.md, line 32 at r2](https://reviewable.io:443/reviews/qtox/blog/7#-Kd25ZsP331Iv_YLQxZi:-Kd25ZsP331Iv_YLQxZj:b-z38dxu) ([raw file](https://github.com/qtox/blog/blob/97a45478111473f47fafac12770650d47fc0b242/_posts/2017-02-15-Maintainer-Wanted.md#L32)):*
> ```Markdown
> 
> If you're interested in helping your favourite FOSS project or want to know
> more, take a look at [this github issue] our ping `Diadlo`, `sudden6` or
> ```

`s/our/or/`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/7)*

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[_posts/2017-02-15-Maintainer-Wanted.md, line 32 at r2](https://reviewable.io:443/reviews/qtox/blog/7#-Kd25ZsP331Iv_YLQxZi:-Kd25uMXYLJJRc7CNGYU:b-896fix) ([raw file](https://github.com/qtox/blog/blob/97a45478111473f47fafac12770650d47fc0b242/_posts/2017-02-15-Maintainer-Wanted.md#L32)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

`s/our/or/`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/7)*

**Comment by zetok** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[_posts/2017-02-15-Maintainer-Wanted.md, line 11 at r3](https://reviewable.io:443/reviews/qtox/blog/7#-Kd27QSOgUs6xTOHtS3z:-Kd27QSOgUs6xTOHtS4-:b9kdrnz) ([raw file](https://github.com/qtox/blog/blob/5a00d47c78332f07b4498aa7b28f5cd35eead9b0/_posts/2017-02-15-Maintainer-Wanted.md#L11)):*
> ```Markdown
> # Outdated Linux packages
> 
> As many of you noticed, the packages for Linux in the[openSUSE Build Service]
> ```

`s/the[/the [/`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/7#-:-Kd27OKPeS__j5CXelqT:bnfp4nl)*

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[_posts/2017-02-15-Maintainer-Wanted.md, line 11 at r3](https://reviewable.io:443/reviews/qtox/blog/7#-Kd27QSOgUs6xTOHtS3z:-Kd27uNexP7y2XoNQo8v:b-896fix) ([raw file](https://github.com/qtox/blog/blob/5a00d47c78332f07b4498aa7b28f5cd35eead9b0/_posts/2017-02-15-Maintainer-Wanted.md#L11)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

`s/the[/the [/`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/7)*

**Comment by zetok** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[_posts/2017-02-15-Maintainer-Wanted.md, line 18 at r4](https://reviewable.io:443/reviews/qtox/blog/7#-Kd28qnFt4zUI4qzqa2H:-Kd28qnGGJgA8A65DApV:b-vbrfzr) ([raw file](https://github.com/qtox/blog/blob/ad960486d26ad6764b3d7fe516d86a2cea9c08f2/_posts/2017-02-15-Maintainer-Wanted.md#L18)):*
> ```Markdown
> 
> Packaging work is mostly about keeping bash scripts for the builds up to date.
> Most of them have already been written, but things break every now and then or
> ```

perhaps link `written` to https://github.com/abbat/tox.pkg ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/7)*

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[_posts/2017-02-15-Maintainer-Wanted.md, line 18 at r4](https://reviewable.io:443/reviews/qtox/blog/7#-Kd28qnFt4zUI4qzqa2H:-Kd29hC3JHA4LbtFqKF8:b-896fix) ([raw file](https://github.com/qtox/blog/blob/ad960486d26ad6764b3d7fe516d86a2cea9c08f2/_posts/2017-02-15-Maintainer-Wanted.md#L18)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

perhaps link `written` to https://github.com/abbat/tox.pkg ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/7)*

**Comment by zetok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/7#-:-Kd29vZTHWjQ6Shj3YJL:bnfp4nl)*

**Pull request merged**
