### PR TITLE
Blog post for v1.12 release

### PR DESCRIPTION
**Pull request by sudden6**
cc: @zetok and @anthonybilinski

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/blog/9)

### CODE REVIEW

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[_posts/2017-10-05-v1.12.0 Release.md, line 22 at r1](https://reviewable.io:443/reviews/qtox/blog/9#-KvZbMFhUEpmZxJptmpU:-KvZbMFilTG1FQnm3hG_:bj5rohr) ([raw file](https://github.com/qtox/blog/blob/5367415c4acd31f496327055a485d8c84de7363a/_posts/2017-10-05-v1.12.0 Release.md#L22)):*
> ```Markdown
> display images with correct orientation, a feature to mass import contacts
> from a file and a new command line switch to open the login window instead of
> a profile.
> ```

This sentence sounds a bit awkward, perhaps it would be better to remake it into a list?

e.g.

```markdown
Notable are:

- integration of the an EXIF library to automatically display images with
  correct orientation
- mass import contacts from a file
- new command line switch to open the login window instead of a profile
```

---

*[_posts/2017-10-05-v1.12.0 Release.md, line 35 at r1](https://reviewable.io:443/reviews/qtox/blog/9#-KvZcT3JiYRPx9jVn8KA:-KvZcT3JiYRPx9jVn8KB:b-bcnria) ([raw file](https://github.com/qtox/blog/blob/5367415c4acd31f496327055a485d8c84de7363a/_posts/2017-10-05-v1.12.0 Release.md#L35)):*
> ```Markdown
> One of the first commits after this release has removed the `qTox.pro` file,
> so for the main program qTox is exclusively using cmake now. Thanks to
> `nurupo` we also have a pretty solid cross-compiling process for Windows now
> ```

Perhaps link to nurupo's gh profile? https://github.com/nurupo/

Also, `s/also//` ?

---

*[_posts/2017-10-05-v1.12.0 Release.md, line 55 at r1](https://reviewable.io:443/reviews/qtox/blog/9#-KvZd0WGb39kEX8Wfpbc:-KvZd0WHRpSf7MVPlWP4:b894xwc) ([raw file](https://github.com/qtox/blog/blob/5367415c4acd31f496327055a485d8c84de7363a/_posts/2017-10-05-v1.12.0 Release.md#L55)):*
> ```Markdown
> Thanks to everybody who made this release happen!
> 
> changelog: https://github.com/qTox/qTox/blob/master/CHANGELOG.md#v1120-2017-10-01
> ```

`changelog` needs brackets: `[changelog]:`

Also, it's more future-proof to link to fixed changelog version: https://github.com/qTox/qTox/blob/v1.12.0/CHANGELOG.md#v1120-2017-10-01

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/9)*

**Comment by anthonybilinski** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[_posts/2017-10-05-v1.12.0 Release.md, line 9 at r1](https://reviewable.io:443/reviews/qtox/blog/9#-KvcUijtJVmMiipbw5Ex:-KvcUijtJVmMiipbw5Ey:b9ipcz3) ([raw file](https://github.com/qtox/blog/blob/5367415c4acd31f496327055a485d8c84de7363a/_posts/2017-10-05-v1.12.0 Release.md#L9)):*
> ```Markdown
> ---
> 
> # Great release great news
> ```

"Great release great news" sounds a little strange. If you're trying to say that it's news about a great release, maybe just "Great release news". This seems like the best to me, it means the same as "News about a great release", if you're trying to say that both the release and the news is great, maybe "Great release; great news" since they are separate ideas.

---

*[_posts/2017-10-05-v1.12.0 Release.md, line 11 at r1](https://reviewable.io:443/reviews/qtox/blog/9#-KvcehvKRiqhf2xr6OfV:-KvcehvLAaMuqZGlVkUT:b-gzj8m2) ([raw file](https://github.com/qtox/blog/blob/5367415c4acd31f496327055a485d8c84de7363a/_posts/2017-10-05-v1.12.0 Release.md#L11)):*
> ```Markdown
> # Great release great news
> 
> We again made this release cycle, mostly due to everybody being on holiday.
> ```

Assuming you're referring to the release deadline, "made this release" instead of "made this release cycle".
does qTox not normally make its release deadlines? why was the release deadline made only because people were on holiday? :P

---

*[_posts/2017-10-05-v1.12.0 Release.md, line 12 at r1](https://reviewable.io:443/reviews/qtox/blog/9#-KvcS8m90RjqmceTboks:-KvcS8m90RjqmceTbokt:b-rfa5g0) ([raw file](https://github.com/qtox/blog/blob/5367415c4acd31f496327055a485d8c84de7363a/_posts/2017-10-05-v1.12.0 Release.md#L12)):*
> ```Markdown
> 
> We again made this release cycle, mostly due to everybody being on holiday.
> Thanks to many contributions this release is has some very nice new features
> ```

"this release is has" -> "this release has"

---

*[_posts/2017-10-05-v1.12.0 Release.md, line 26 at r1](https://reviewable.io:443/reviews/qtox/blog/9#-KvcSqWReEID6frSeO6i:-KvcSqWReEID6frSeO6j:b-72o3mi) ([raw file](https://github.com/qtox/blog/blob/5367415c4acd31f496327055a485d8c84de7363a/_posts/2017-10-05-v1.12.0 Release.md#L26)):*
> ```Markdown
> # Experimental echo cancelling
> 
> qTox received an experimental audio backend that provides echo cancelling
> ```

"received" seems like it doesn't fit. It sounds like it was gifted or given to us. Maybe "added", "integrated", or "included" would be better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/9)*

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[_posts/2017-10-05-v1.12.0 Release.md, line 9 at r1](https://reviewable.io:443/reviews/qtox/blog/9#-KvcUijtJVmMiipbw5Ex:-KvnRAlydMP6dUhHTLAM:b-896fix) ([raw file](https://github.com/qtox/blog/blob/5367415c4acd31f496327055a485d8c84de7363a/_posts/2017-10-05-v1.12.0 Release.md#L9)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

"Great release great news" sounds a little strange. If you're trying to say that it's news about a great release, maybe just "Great release news". This seems like the best to me, it means the same as "News about a great release", if you're trying to say that both the release and the news is great, maybe "Great release; great news" since they are separate ideas.
</blockquote></details>

Done.

---

*[_posts/2017-10-05-v1.12.0 Release.md, line 11 at r1](https://reviewable.io:443/reviews/qtox/blog/9#-KvcehvKRiqhf2xr6OfV:-KvnR73irEMxN3yoRyfy:b-4w160n) ([raw file](https://github.com/qtox/blog/blob/5367415c4acd31f496327055a485d8c84de7363a/_posts/2017-10-05-v1.12.0 Release.md#L11)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Assuming you're referring to the release deadline, "made this release" instead of "made this release cycle".
does qTox not normally make its release deadlines? why was the release deadline made only because people were on holiday? :P
</blockquote></details>

Done. Forgot some words :D

---

*[_posts/2017-10-05-v1.12.0 Release.md, line 12 at r1](https://reviewable.io:443/reviews/qtox/blog/9#-KvcS8m90RjqmceTboks:-KvnRDb-AeUjI_pPQagU:b-896fix) ([raw file](https://github.com/qtox/blog/blob/5367415c4acd31f496327055a485d8c84de7363a/_posts/2017-10-05-v1.12.0 Release.md#L12)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

"this release is has" -> "this release has"
</blockquote></details>

Done.

---

*[_posts/2017-10-05-v1.12.0 Release.md, line 22 at r1](https://reviewable.io:443/reviews/qtox/blog/9#-KvZbMFhUEpmZxJptmpU:-KvnRXwbNoYaYzlyoxQZ:b-896fix) ([raw file](https://github.com/qtox/blog/blob/5367415c4acd31f496327055a485d8c84de7363a/_posts/2017-10-05-v1.12.0 Release.md#L22)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

This sentence sounds a bit awkward, perhaps it would be better to remake it into a list?

e.g.

```markdown
Notable are:

- integration of the an EXIF library to automatically display images with
  correct orientation
- mass import contacts from a file
- new command line switch to open the login window instead of a profile
```
</blockquote></details>

Done.

---

*[_posts/2017-10-05-v1.12.0 Release.md, line 26 at r1](https://reviewable.io:443/reviews/qtox/blog/9#-KvcSqWReEID6frSeO6i:-KvnRf1Sfo9n_Le8mr4S:b-896fix) ([raw file](https://github.com/qtox/blog/blob/5367415c4acd31f496327055a485d8c84de7363a/_posts/2017-10-05-v1.12.0 Release.md#L26)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

"received" seems like it doesn't fit. It sounds like it was gifted or given to us. Maybe "added", "integrated", or "included" would be better.
</blockquote></details>

Done.

---

*[_posts/2017-10-05-v1.12.0 Release.md, line 35 at r1](https://reviewable.io:443/reviews/qtox/blog/9#-KvZcT3JiYRPx9jVn8KA:-KvnS2x5UL3BCXHFHLiF:b-896fix) ([raw file](https://github.com/qtox/blog/blob/5367415c4acd31f496327055a485d8c84de7363a/_posts/2017-10-05-v1.12.0 Release.md#L35)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Perhaps link to nurupo's gh profile? https://github.com/nurupo/

Also, `s/also//` ?
</blockquote></details>

Done.

---

*[_posts/2017-10-05-v1.12.0 Release.md, line 55 at r1](https://reviewable.io:443/reviews/qtox/blog/9#-KvZd0WGb39kEX8Wfpbc:-KvnSCooWSYU12yeWPav:b-896fix) ([raw file](https://github.com/qtox/blog/blob/5367415c4acd31f496327055a485d8c84de7363a/_posts/2017-10-05-v1.12.0 Release.md#L55)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

`changelog` needs brackets: `[changelog]:`

Also, it's more future-proof to link to fixed changelog version: https://github.com/qTox/qTox/blob/v1.12.0/CHANGELOG.md#v1120-2017-10-01
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/9)*

**Comment by anthonybilinski** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/9#-:-Kw1JaLB0ubk3ndj44Nw:bnfp4nl)*

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[_posts/2017-10-05-v1.12.0 Release.md, line 37 at r2](https://reviewable.io:443/reviews/qtox/blog/9#-Kw1LqRcGuOxniuOcPyW:-Kw1LqRd9tboXi-tKkEP:b-5wyed1) ([raw file](https://github.com/qtox/blog/blob/e11d62225ebaec40a38ae61263071233f9e74235/_posts/2017-10-05-v1.12.0 Release.md#L37)):*
> ```Markdown
> One of the first commits after this release has removed the `qTox.pro` file,
> so for the main program qTox is exclusively using cmake now. Thanks to
> [nurupo](https://github.com/nurupo) we also have a pretty solid
> ```

`also` in this line seems to be unnecessary?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/9)*

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[_posts/2017-10-05-v1.12.0 Release.md, line 37 at r2](https://reviewable.io:443/reviews/qtox/blog/9#-Kw1LqRcGuOxniuOcPyW:-Kw1OOJyxqUMUAByFKew:b-896fix) ([raw file](https://github.com/qtox/blog/blob/e11d62225ebaec40a38ae61263071233f9e74235/_posts/2017-10-05-v1.12.0 Release.md#L37)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

`also` in this line seems to be unnecessary?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/9)*

**Comment by zetok** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/9#-:-Kw1P-80ul7i3Emwqrf-:bnfp4nl)*

**Pull request merged**
