### PR TITLE
Add a blog post about features in version 1.16

### PR DESCRIPTION
**Pull request by tox-user**
@sudden6 please review

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/blog/15)

### CODE REVIEW

**Comment by sudden6** [comment]
Sorry for answering late...

I think we should only release the blog post once we tagged it, else the post reads very well.

**Comment by tox-user** [comment]
It's not a release blog post. It's supposed to be published before the release.

**Comment by tox-user** [comment]
I merged it as https://github.com/qTox/blog/commit/eac6d678ba1408bca5efc521c8b12e467a6f0da2 and now it's availble at https://qtox.github.io/blog/2018/06/28/qTox-1.16-features.html but images don't load for me.

**Comment by tox-user** [comment]
Fixed.

**Pull request closed without merging**
