### PR TITLE
Add post for the 1.7 release

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/blog/5)

### CODE REVIEW

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[_posts/2016-12-25-Autoupdater-bug-and-v1.7.0-release.md, line 23 at r1](https://reviewable.io:443/reviews/qtox/blog/5#-KZr1PDmfAZyqXQkuokX:-KZr1PDmfAZyqXQkuokY:ba9lz3s) ([raw file](https://github.com/qtox/blog/blob/6a22ce02721d576fbcffc7449196ade26de1431d/_posts/2016-12-25-Autoupdater-bug-and-v1.7.0-release.md#L23)):*
> ```Markdown
> # v1.7.0 release
> 
> Due to speeded up release cycle, `1.7` is a slightly smaller release. Some bugs
> ```

Due to the speeded up

---

*[_posts/2016-12-25-Autoupdater-bug-and-v1.7.0-release.md, line 36 at r1](https://reviewable.io:443/reviews/qtox/blog/5#-KZr1Ko1mlBY56Ygtgcd:-KZr1Ko2E4o8ICusQoXw:b-7fcp77) ([raw file](https://github.com/qtox/blog/blob/6a22ce02721d576fbcffc7449196ade26de1431d/_posts/2016-12-25-Autoupdater-bug-and-v1.7.0-release.md#L36)):*
> ```Markdown
> ## Switch to TokTok
> 
> For some time toxcore's development was halted. TokTok project helped with the
> ```

The TokTok project

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/5)*

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[_posts/2016-12-25-Autoupdater-bug-and-v1.7.0-release.md, line 23 at r1](https://reviewable.io:443/reviews/qtox/blog/5#-KZr1PDmfAZyqXQkuokX:-KZr2mXS2lm0_8maSlQt:b-896fix) ([raw file](https://github.com/qtox/blog/blob/6a22ce02721d576fbcffc7449196ade26de1431d/_posts/2016-12-25-Autoupdater-bug-and-v1.7.0-release.md#L23)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Due to the speeded up
</blockquote></details>

Done.

---

*[_posts/2016-12-25-Autoupdater-bug-and-v1.7.0-release.md, line 36 at r1](https://reviewable.io:443/reviews/qtox/blog/5#-KZr1Ko1mlBY56Ygtgcd:-KZr2oQnMqTriTyqSxWK:b-896fix) ([raw file](https://github.com/qtox/blog/blob/6a22ce02721d576fbcffc7449196ade26de1431d/_posts/2016-12-25-Autoupdater-bug-and-v1.7.0-release.md#L36)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

The TokTok project
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/5)*

**Comment by sudden6** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/5)*

**Comment by sudden6** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/5#-:-KZr6IGbhhMVQvyAEMjp:bg7igkv)*

**Comment by sudden6** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/5#-:-KZr6d4OMZyV0A-qiq0a:bnfp4nl)*

**Comment by sudden6** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/5#-:-KZr7LdrW8pmce02wzq2:bnfp4nl)*

**Comment by sudden6** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/blog/5)*

**Pull request merged**
