### PR TITLE
Add a blog post for 1.16.0 release

### PR DESCRIPTION
**Pull request by tox-user**
This change is [Reviewable](https://reviewable.io/reviews/qtox/blog/16)

### CODE REVIEW

**Review by sudden6 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/blog/16)* status: 0 of 2 LGTMs obtained (waiting on @anthonybilinski and @sudden6)

___
*[_posts/2018-07-05-v1.16.0 Release.md, line 9 at r1](https://reviewable.io/reviews/qtox/blog/16#-LGgUctX1rdTChkP1SXy:-LGgUctX1rdTChkP1SXz:bpxyf7h) ([raw file](https://github.com/qtox/blog/blob/ea200f9650e0f60659badae0ae10c4f0e7385000/_posts/2018-07-05-v1.16.0 Release.md#L9)):*
> ```Markdown
> ---
> 
> Hi! Version 1.16.0 is now released. It contains a few big features and a lot of small improvements. You can find out more details about some of them here: [features in qTox 1.16](https://qtox.github.io/blog/2018/06/28/qTox-1.16-features.html).
> ```

version is actually 1.16.1 since yesterday

**Review by anthonybilinski — APPROVED** [review]
:lgtm: after version bump to 1.16.1

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/blog/16#-:-LGlxzSZE415eZi9_voa:b-w9u4th)* status: 0 of 2 LGTMs obtained, and 1 stale (waiting on @anthonybilinski and @sudden6)

**Review by anthonybilinski — APPROVED** [review]
try again for the check: :lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/qtox/blog/16#-:-LGlyBhYCxjT_U8BKavC:b-vcop9w)* status: 1 of 2 LGTMs obtained (waiting on @sudden6)

**Comment by tox-user** [comment]
Done. Also added a link to the changelog.

**Review by sudden6 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/blog/16)* status: 1 of 2 LGTMs obtained (waiting on @sudden6)

___
*[_posts/2018-07-07-v1.16.1 Release.md, line 27 at r2](https://reviewable.io/reviews/qtox/blog/16#-LGpt3Oe4bBGDO_TSiZX:-LGpt3OfEB9Z2QE0RQB4:b8kx9g7) ([raw file](https://github.com/qtox/blog/blob/9be3b1964c20e5f677c2cdd0ace4d62263a8d51e/_posts/2018-07-07-v1.16.1 Release.md#L27)):*
> ```Markdown
> - fixed bugs in simple_make.sh script
> 
> Full changelog: [https://github.com/qTox/qTox/blob/master/CHANGELOG.md](https://github.com/qTox/qTox/blob/master/CHANGELOG.md)
> ```

you link to the `master` branch which will change in the future, better select the actual tag.

**Comment by tox-user** [comment]
Done.

**Pull request merged**
